const data = [
  {
    id: 1,
    name: "Red Potion",
    image_url: "./potion-icons/red-potion.png",
    buyCost: 43,
    sellPrice: 21,
  },
  {
    id: 2,
    name: "Red Vial",
    image_url: "./potion-icons/red-vial.png",
    buyCost: 34,
    sellPrice: 17,
  },
  {
    id: 3,
    name: "Red Tincture",
    image_url: "./potion-icons/red-tincture.png",
    buyCost: 51,
    sellPrice: 25,
  },
  {
    id: 4,
    name: "Red Poison",
    image_url: "./potion-icons/red-poison.png",
    buyCost: 24,
    sellPrice: 12,
  },
  {
    id: 5,
    name: "Black Potion",
    image_url: "./potion-icons/black-potion.png",
    buyCost: 35,
    sellPrice: 17,
  },
  {
    id: 6,
    name: "Black Vial",
    image_url: "./potion-icons/black-vial.png",
    buyCost: 71,
    sellPrice: 35,
  },
  {
    id: 7,
    name: "Black Tincture",
    image_url: "./potion-icons/black-tincture.png",
    buyCost: 32,
    sellPrice: 16,
  },
  {
    id: 8,
    name: "Black Poison",
    image_url: "./potion-icons/black-poison.png",
    buyCost: 38,
    sellPrice: 19,
  },
  {
    id: 9,
    name: "Blue Potion",
    image_url: "./potion-icons/blue-potion.png",
    buyCost: 51,
    sellPrice: 25,
  },
  {
    id: 10,
    name: "Blue Vial",
    image_url: "./potion-icons/blue-vial.png",
    buyCost: 29,
    sellPrice: 14,
  },
  {
    id: 11,
    name: "Blue Tincture",
    image_url: "./potion-icons/blue-tincture.png",
    buyCost: 49,
    sellPrice: 24,
  },
  {
    id: 12,
    name: "Blue Poison",
    image_url: "./potion-icons/blue-poison.png",
    buyCost: 27,
    sellPrice: 13,
  },
  {
    id: 13,
    name: "Gold Potion",
    image_url: "./potion-icons/gold-potion.png",
    buyCost: 69,
    sellPrice: 34,
  },
  {
    id: 14,
    name: "Gold Vial",
    image_url: "./potion-icons/gold-vial.png",
    buyCost: 101,
    sellPrice: 50,
  },
  {
    id: 15,
    name: "Gold Tincture",
    image_url: "./potion-icons/gold-tincture.png",
    buyCost: 48,
    sellPrice: 24,
  },
  {
    id: 16,
    name: "Gold Poison",
    image_url: "./potion-icons/gold-poison.png",
    buyCost: 84,
    sellPrice: 42,
  },
  {
    id: 17,
    name: "Green Potion",
    image_url: "./potion-icons/green-potion.png",
    buyCost: 74,
    sellPrice: 37,
  },
  {
    id: 18,
    name: "Green Vial",
    image_url: "./potion-icons/green-vial.png",
    buyCost: 111,
    sellPrice: 55,
  },
  {
    id: 19,
    name: "Green Tincture",
    image_url: "./potion-icons/green-tincture.png",
    buyCost: 93,
    sellPrice: 46,
  },
  {
    id: 20,
    name: "Green Poison",
    image_url: "./potion-icons/green-poison.png",
    buyCost: 97,
    sellPrice: 48,
  },
  {
    id: 21,
    name: "Pink Potion",
    image_url: "./potion-icons/pink-potion.png",
    buyCost: 75,
    sellPrice: 37,
  },
  {
    id: 22,
    name: "Pink Vial",
    image_url: "./potion-icons/pink-vial.png",
    buyCost: 97,
    sellPrice: 48,
  },
  {
    id: 23,
    name: "Pink Tincture",
    image_url: "./potion-icons/pink-tincture.png",
    buyCost: 95,
    sellPrice: 47,
  },
  {
    id: 24,
    name: "Pink Poison",
    image_url: "./potion-icons/pink-poison.png",
    buyCost: 81,
    sellPrice: 40,
  },
  {
    id: 25,
    name: "Purple Potion",
    image_url: "./potion-icons/purple-potion.png",
    buyCost: 84,
    sellPrice: 42,
  },
  {
    id: 26,
    name: "Purple Vial",
    image_url: "./potion-icons/purple-vial.png",
    buyCost: 81,
    sellPrice: 40,
  },
  {
    id: 27,
    name: "Purple Tincture",
    image_url: "./potion-icons/purple-tincture.png",
    buyCost: 107,
    sellPrice: 53,
  },
  {
    id: 28,
    name: "Purple Poison",
    image_url: "./potion-icons/purple-poison.png",
    buyCost: 112,
    sellPrice: 56,
  },
  {
    id: 29,
    name: "Teal Potion",
    image_url: "./potion-icons/teal-potion.png",
    buyCost: 110,
    sellPrice: 55,
  },
  {
    id: 30,
    name: "Teal Vial",
    image_url: "./potion-icons/teal-vial.png",
    buyCost: 42,
    sellPrice: 21,
  },
  {
    id: 31,
    name: "Teal Tincture",
    image_url: "./potion-icons/teal-tincture.png",
    buyCost: 90,
    sellPrice: 45,
  },
  {
    id: 32,
    name: "Teal Poison",
    image_url: "./potion-icons/teal-poison.png",
    buyCost: 27,
    sellPrice: 13,
  },
  {
    id: 33,
    name: "White Potion",
    image_url: "./potion-icons/white-potion.png",
    buyCost: 21,
    sellPrice: 10,
  },
  {
    id: 34,
    name: "White Vial",
    image_url: "./potion-icons/white-vial.png",
    buyCost: 24,
    sellPrice: 12,
  },
  {
    id: 35,
    name: "White Tincture",
    image_url: "./potion-icons/white-tincture.png",
    buyCost: 61,
    sellPrice: 30,
  },
  {
    id: 36,
    name: "White Poison",
    image_url: "./potion-icons/white-poison.png",
    buyCost: 102,
    sellPrice: 51,
  },
  {
    id: 37,
    name: "Yellow Potion",
    image_url: "./potion-icons/yellow-potion.png",
    buyCost: 70,
    sellPrice: 35,
  },
  {
    id: 38,
    name: "Yellow Vial",
    image_url: "./potion-icons/yellow-vial.png",
    buyCost: 81,
    sellPrice: 40,
  },
  {
    id: 39,
    name: "Yellow Tincture",
    image_url: "./potion-icons/yellow-tincture.png",
    buyCost: 115,
    sellPrice: 57,
  },
  {
    id: 40,
    name: "Yellow Poison",
    image_url: "./potion-icons/yellow-poison.png",
    buyCost: 97,
    sellPrice: 48,
  },
];
export default data;
